[project]
name = "ccg-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "deprecated>=1.3.1",
    "fastapi[standard]>=0.129.0",
    "huey>=2.6.0",
    "icecream>=2.1.10",
    "numpy>=2.4.2",
    "orjson>=3.11.7",
    "psutil>=7.2.2",
    "pydantic>=2.12.5",
    "pydub>=0.25.1",
    "pyyaml>=6.0.2",
    "pylance>=2.0.1",
    "pylint>=4.0.5",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "qqmusic-api-python>=0.4.1",
    "redis>=7.2.0",
    "rich>=14.3.2",
    "sqlalchemy>=2.0.43",
    "uvicorn>=0.40.0",
    "yapf>=0.43.0",
]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -s"
testpaths = ["tests"]
pythonpath = ["."]

[tool.yapf]
based_on_style = "google"      # 基础风格: pep8 / google / facebook / chromium
indent_width = 4             # 缩进空格数
column_limit = 88            # 每行最大字符数
align_closing_bracket_with_visual_indent = true  # 对齐闭括号

[tool.pylint]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pylint>=4.0.5",
]
