"""simplify_user_room_relationship

Revision ID: 0e1b75932cca
Revises: 55dce11b4da2
Create Date: 2026-02-21 00:30:26.447399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0e1b75932cca'
down_revision: Union[str, Sequence[str], None] = '55dce11b4da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rooms_host_user_id_fkey'),
                       'rooms',
                       type_='foreignkey')
    op.drop_column('rooms', 'host_user_id')
    op.add_column('users', sa.Column('room_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_owner', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_foreign_key(None,
                          'users',
                          'rooms', ['room_id'], ['id'],
                          ondelete='SET NULL')
    op.drop_column('users', 'display_suffix')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('display_suffix',
                  sa.VARCHAR(),
                  autoincrement=False,
                  nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_owner')
    op.drop_column('users', 'room_id')
    op.add_column(
        'rooms',
        sa.Column('host_user_id',
                  sa.INTEGER(),
                  autoincrement=False,
                  nullable=True))
    op.create_foreign_key(op.f('rooms_host_user_id_fkey'), 'rooms', 'users',
                          ['host_user_id'], ['id'])
    # ### end Alembic commands ###
