"""add_test_audio_song_id_to_room

Revision ID: 21f8f60c55cf
Revises: b3f9324623e2
Create Date: 2026-04-03 18:06:23.465296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f8f60c55cf'
down_revision: Union[str, Sequence[str], None] = 'b3f9324623e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cookie_configs', 'source',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cookie_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('rooms', sa.Column('test_audio_song_id', sa.Integer(), nullable=True, comment='自定义 test_audio 的歌曲 ID，-1 表示使用默认 CDN BGM，NULL 表示未设置'))
    op.create_foreign_key(None, 'rooms', 'songs', ['test_audio_song_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'test_audio_song_id')
    op.alter_column('cookie_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('cookie_configs', 'source',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'manual'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
