"""fix album model fk

Revision ID: 29250e84cfe9
Revises: 3d24e54cc3ff
Create Date: 2026-02-26 16:15:55.918474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29250e84cfe9'
down_revision: Union[str, Sequence[str], None] = '3d24e54cc3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('album_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'songs', 'albums', ['album_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'album_id')
    # ### end Alembic commands ###
