"""add round_state field to room

Revision ID: 34916e1c9328
Revises: 4f1599ff9a86
Create Date: 2026-03-07 11:04:21.306502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34916e1c9328'
down_revision: Union[str, Sequence[str], None] = '4f1599ff9a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('round_state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'round_state')
    # ### end Alembic commands ###
