"""fix model

Revision ID: 3bc461aa5b4a
Revises: c854768192ca
Create Date: 2026-02-25 20:04:53.027916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc461aa5b4a'
down_revision: Union[str, Sequence[str], None] = 'c854768192ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'playlist_id')
    op.add_column('tag_groups', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag_groups', 'description')
    op.add_column('rooms', sa.Column('playlist_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
