"""add room title

Revision ID: 40c095b3cf92
Revises: ebb3be07a6c7
Create Date: 2026-02-25 22:14:58.419094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '40c095b3cf92'
down_revision: Union[str, Sequence[str], None] = 'ebb3be07a6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'title')
    # ### end Alembic commands ###
