"""fix models

Revision ID: 53a8874bf238
Revises: d7048550ae08
Create Date: 2026-02-25 17:06:09.193350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a8874bf238'
down_revision: Union[str, Sequence[str], None] = 'd7048550ae08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_group_tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tag_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'group_id')
    )
    op.drop_constraint(op.f('player_answers_room_id_fkey'), 'player_answers', type_='foreignkey')
    op.drop_constraint(op.f('player_answers_user_id_fkey'), 'player_answers', type_='foreignkey')
    op.drop_constraint(op.f('player_answers_song_id_fkey'), 'player_answers', type_='foreignkey')
    op.create_foreign_key(None, 'player_answers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'player_answers', 'songs', ['song_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'player_answers', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('room_songs_song_id_fkey'), 'room_songs', type_='foreignkey')
    op.create_foreign_key(None, 'room_songs', 'songs', ['song_id'], ['id'], ondelete='CASCADE')
    op.add_column('rooms', sa.Column('tag_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'tag_groups', ['tag_group_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('scores_room_id_fkey'), 'scores', type_='foreignkey')
    op.drop_constraint(op.f('scores_user_id_fkey'), 'scores', type_='foreignkey')
    op.create_foreign_key(None, 'scores', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scores', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.alter_column('song_description_history', 'judged_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('song_description_history', 'room_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('song_description_history_song_id_fkey'), 'song_description_history', type_='foreignkey')
    op.drop_constraint(op.f('song_description_history_room_id_fkey'), 'song_description_history', type_='foreignkey')
    op.drop_constraint(op.f('song_description_history_judged_by_user_id_fkey'), 'song_description_history', type_='foreignkey')
    op.create_foreign_key(None, 'song_description_history', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'song_description_history', 'users', ['judged_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'song_description_history', 'songs', ['song_id'], ['id'], ondelete='CASCADE')
    op.alter_column('song_tag_history', 'judged_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('song_tag_history', 'room_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('song_tag_history_tag_id_fkey'), 'song_tag_history', type_='foreignkey')
    op.drop_constraint(op.f('song_tag_history_song_id_fkey'), 'song_tag_history', type_='foreignkey')
    op.drop_constraint(op.f('song_tag_history_room_id_fkey'), 'song_tag_history', type_='foreignkey')
    op.drop_constraint(op.f('song_tag_history_judged_by_user_id_fkey'), 'song_tag_history', type_='foreignkey')
    op.create_foreign_key(None, 'song_tag_history', 'songs', ['song_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'song_tag_history', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'song_tag_history', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'song_tag_history', 'users', ['judged_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('songlist_songs_song_id_fkey'), 'songlist_songs', type_='foreignkey')
    op.create_foreign_key(None, 'songlist_songs', 'songs', ['song_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tag_groups_room_id_fkey'), 'tag_groups', type_='foreignkey')
    op.drop_column('tag_groups', 'room_id')
    op.drop_constraint(op.f('uq_tag_group_name'), 'tags', type_='unique')
    op.drop_constraint(op.f('tags_group_id_fkey'), 'tags', type_='foreignkey')
    op.drop_column('tags', 'group_id')
    op.create_index('idx_users_room_id', 'users', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_room_id', table_name='users')
    op.add_column('tags', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tags_group_id_fkey'), 'tags', 'tag_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_tag_group_name'), 'tags', ['group_id', 'name'], postgresql_nulls_not_distinct=False)
    op.add_column('tag_groups', sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tag_groups_room_id_fkey'), 'tag_groups', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'songlist_songs', type_='foreignkey')
    op.create_foreign_key(op.f('songlist_songs_song_id_fkey'), 'songlist_songs', 'songs', ['song_id'], ['id'])
    op.drop_constraint(None, 'song_tag_history', type_='foreignkey')
    op.drop_constraint(None, 'song_tag_history', type_='foreignkey')
    op.drop_constraint(None, 'song_tag_history', type_='foreignkey')
    op.drop_constraint(None, 'song_tag_history', type_='foreignkey')
    op.create_foreign_key(op.f('song_tag_history_judged_by_user_id_fkey'), 'song_tag_history', 'users', ['judged_by_user_id'], ['id'])
    op.create_foreign_key(op.f('song_tag_history_room_id_fkey'), 'song_tag_history', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('song_tag_history_song_id_fkey'), 'song_tag_history', 'songs', ['song_id'], ['id'])
    op.create_foreign_key(op.f('song_tag_history_tag_id_fkey'), 'song_tag_history', 'tags', ['tag_id'], ['id'])
    op.alter_column('song_tag_history', 'room_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('song_tag_history', 'judged_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'song_description_history', type_='foreignkey')
    op.drop_constraint(None, 'song_description_history', type_='foreignkey')
    op.drop_constraint(None, 'song_description_history', type_='foreignkey')
    op.create_foreign_key(op.f('song_description_history_judged_by_user_id_fkey'), 'song_description_history', 'users', ['judged_by_user_id'], ['id'])
    op.create_foreign_key(op.f('song_description_history_room_id_fkey'), 'song_description_history', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('song_description_history_song_id_fkey'), 'song_description_history', 'songs', ['song_id'], ['id'])
    op.alter_column('song_description_history', 'room_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('song_description_history', 'judged_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.create_foreign_key(op.f('scores_user_id_fkey'), 'scores', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('scores_room_id_fkey'), 'scores', 'rooms', ['room_id'], ['id'])
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'tag_group_id')
    op.drop_constraint(None, 'room_songs', type_='foreignkey')
    op.create_foreign_key(op.f('room_songs_song_id_fkey'), 'room_songs', 'songs', ['song_id'], ['id'])
    op.drop_constraint(None, 'player_answers', type_='foreignkey')
    op.drop_constraint(None, 'player_answers', type_='foreignkey')
    op.drop_constraint(None, 'player_answers', type_='foreignkey')
    op.create_foreign_key(op.f('player_answers_song_id_fkey'), 'player_answers', 'songs', ['song_id'], ['id'])
    op.create_foreign_key(op.f('player_answers_user_id_fkey'), 'player_answers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('player_answers_room_id_fkey'), 'player_answers', 'rooms', ['room_id'], ['id'])
    op.drop_table('tag_group_tags')
    # ### end Alembic commands ###
