"""initial_schema

Revision ID: 55dce11b4da2
Revises: 
Create Date: 2026-02-20 22:56:41.004823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '55dce11b4da2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'songs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('platform', sa.String(), nullable=True),
        sa.Column('platform_song_id', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('artist', sa.String(), nullable=True),
        sa.Column('cover_url', sa.String(), nullable=True),
        sa.Column('audio_url', sa.String(), nullable=True),
        sa.Column('cached_path', sa.String(), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('platform',
                            'platform_song_id',
                            name='uq_song_platform_id'))
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('display_suffix', sa.String(), nullable=True),
        sa.Column('created_at',
                  sa.DateTime(),
                  server_default=sa.text('(CURRENT_TIMESTAMP)'),
                  nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'rooms', sa.Column('id', sa.String(), nullable=False),
        sa.Column('host_user_id', sa.Integer(), nullable=True),
        sa.Column('playlist_id', sa.String(), nullable=True),
        sa.Column('tag_groups_json', sa.JSON(), nullable=True),
        sa.Column('status', sa.Integer(), nullable=False),
        sa.Column('created_at',
                  sa.DateTime(),
                  server_default=sa.text('(CURRENT_TIMESTAMP)'),
                  nullable=False),
        sa.Column('ended_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['host_user_id'],
            ['users.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'player_answers',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('room_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('song_id', sa.Integer(), nullable=False),
        sa.Column('round_index', sa.Integer(), nullable=True),
        sa.Column('selected_tag_ids', sa.JSON(), nullable=True),
        sa.Column('description_text', sa.Text(), nullable=True),
        sa.Column('answer_order', sa.Integer(), nullable=True),
        sa.Column('created_at',
                  sa.DateTime(),
                  server_default=sa.text('(CURRENT_TIMESTAMP)'),
                  nullable=False),
        sa.ForeignKeyConstraint(
            ['room_id'],
            ['rooms.id'],
        ), sa.ForeignKeyConstraint(
            ['song_id'],
            ['songs.id'],
        ), sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'room_songs', sa.Column('room_id', sa.String(), nullable=False),
        sa.Column('song_id', sa.Integer(), nullable=False),
        sa.Column('song_order', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['song_id'],
            ['songs.id'],
        ), sa.PrimaryKeyConstraint('room_id', 'song_id'))
    op.create_table(
        'scores',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('room_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('round_index', sa.Integer(), nullable=True),
        sa.Column('score_delta', sa.Integer(), nullable=True),
        sa.Column('total_score', sa.Integer(), nullable=True),
        sa.Column('created_at',
                  sa.DateTime(),
                  server_default=sa.text('(CURRENT_TIMESTAMP)'),
                  nullable=False),
        sa.ForeignKeyConstraint(
            ['room_id'],
            ['rooms.id'],
        ), sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'song_description_history',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('song_id', sa.Integer(), nullable=False),
        sa.Column('description_text', sa.Text(), nullable=False),
        sa.Column('is_correct', sa.Boolean(), nullable=False),
        sa.Column('judged_by_user_id', sa.Integer(), nullable=False),
        sa.Column('room_id', sa.String(), nullable=False),
        sa.Column('created_at',
                  sa.DateTime(),
                  server_default=sa.text('(CURRENT_TIMESTAMP)'),
                  nullable=False),
        sa.ForeignKeyConstraint(
            ['judged_by_user_id'],
            ['users.id'],
        ), sa.ForeignKeyConstraint(
            ['room_id'],
            ['rooms.id'],
        ), sa.ForeignKeyConstraint(
            ['song_id'],
            ['songs.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'tag_groups',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('room_id', sa.String(), nullable=True),
        sa.Column('created_at',
                  sa.DateTime(),
                  server_default=sa.text('(CURRENT_TIMESTAMP)'),
                  nullable=False),
        sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['tag_groups.id'],
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('group_id', 'name', name='uq_tag_group_name'))
    op.create_table(
        'song_tag_history',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('song_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.Column('judged_by_user_id', sa.Integer(), nullable=False),
        sa.Column('room_id', sa.String(), nullable=False),
        sa.Column('created_at',
                  sa.DateTime(),
                  server_default=sa.text('(CURRENT_TIMESTAMP)'),
                  nullable=False),
        sa.ForeignKeyConstraint(
            ['judged_by_user_id'],
            ['users.id'],
        ), sa.ForeignKeyConstraint(
            ['room_id'],
            ['rooms.id'],
        ), sa.ForeignKeyConstraint(
            ['song_id'],
            ['songs.id'],
        ), sa.ForeignKeyConstraint(
            ['tag_id'],
            ['tags.id'],
        ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_tag_history')
    op.drop_table('tags')
    op.drop_table('tag_groups')
    op.drop_table('song_description_history')
    op.drop_table('scores')
    op.drop_table('room_songs')
    op.drop_table('player_answers')
    op.drop_table('rooms')
    op.drop_table('users')
    op.drop_table('songs')
    # ### end Alembic commands ###
