"""Add persistence fields to Room and User models

Revision ID: 5893cdbc207c
Revises: d7048550ae08
Create Date: 2026-02-23 22:08:06.615777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5893cdbc207c'
down_revision: Union[str, Sequence[str], None] = 'd7048550ae08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('title', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('rooms', sa.Column('rounds_data', sa.JSON(), nullable=True))
    op.add_column('rooms', sa.Column('final_scores_json', sa.JSON(), nullable=True))
    op.alter_column('rooms', 'status',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('users', sa.Column('joined_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('users', sa.Column('left_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'left_at')
    op.drop_column('users', 'joined_at')
    op.alter_column('rooms', 'status',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('rooms', 'final_scores_json')
    op.drop_column('rooms', 'rounds_data')
    op.drop_column('rooms', 'started_at')
    op.drop_column('rooms', 'description')
    op.drop_column('rooms', 'title')
    # ### end Alembic commands ###
