"""add user online status

Revision ID: 59a73e89aff7
Revises: f4206f0da7c2
Create Date: 2026-02-28 23:17:44.969744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '59a73e89aff7'
down_revision: Union[str, Sequence[str], None] = 'f4206f0da7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('online', sa.Boolean(), nullable=True, server_default=sa.false()))
    op.execute('UPDATE users SET online = FALSE')
    op.alter_column('users', 'online', nullable=False, server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'online')
    # ### end Alembic commands ###
