"""add_times_selected_to_song_description_history

Revision ID: 67b82b9f3c4a
Revises: e801682d6327
Create Date: 2026-03-21 20:51:08.826480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b82b9f3c4a'
down_revision: Union[str, Sequence[str], None] = 'e801682d6327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song_description_history', sa.Column('times_selected', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song_description_history', 'times_selected')
    # ### end Alembic commands ###
