"""remove audio_url

Revision ID: 8831ddf1f63c
Revises: f5534bb260c6
Create Date: 2026-03-05 17:07:33.210914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8831ddf1f63c'
down_revision: Union[str, Sequence[str], None] = 'f5534bb260c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'audio_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'songs', sa.Column('audio_url',
                           sa.VARCHAR(),
                           autoincrement=False,
                           nullable=True))
    # ### end Alembic commands ###
