"""add m2m to tag group and room

Revision ID: ab74b04c1f4c
Revises: 3bc461aa5b4a
Create Date: 2026-02-25 21:02:11.003606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab74b04c1f4c'
down_revision: Union[str, Sequence[str], None] = '3bc461aa5b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
