"""add room show_answer flag

Revision ID: b3f9324623e2
Revises: 16259d859285
Create Date: 2026-04-01 15:38:02.825832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f9324623e2'
down_revision: Union[str, Sequence[str], None] = '16259d859285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'rooms',
        sa.Column('show_answer', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'show_answer')
    # ### end Alembic commands ###
