"""fix room tag_groups

Revision ID: b61d21916e3e
Revises: d2f57632fedc
Create Date: 2026-02-26 10:01:02.193920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b61d21916e3e'
down_revision: Union[str, Sequence[str], None] = 'd2f57632fedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
