"""add m2m to tag group and room

Revision ID: bd1cd4352f29
Revises: ab74b04c1f4c
Create Date: 2026-02-25 21:03:41.981365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bd1cd4352f29'
down_revision: Union[str, Sequence[str], None] = 'ab74b04c1f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tag_groups_rooms', sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('room_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['tag_groups.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('group_id', 'room_id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_groups_rooms')
    # ### end Alembic commands ###
