"""fix relationships and add token field of users

Revision ID: c854768192ca
Revises: 53a8874bf238
Create Date: 2026-02-25 18:11:29.590376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c854768192ca'
down_revision: Union[str, Sequence[str], None] = '53a8874bf238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'tag_groups_json')
    op.add_column('users', sa.Column('token', sa.String(), nullable=False, comment='用于用户身份验证的唯一令牌'))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_unique_constraint('uq_users_room_id_username', 'users', ['room_id', 'username'])
    op.create_unique_constraint(None, 'users', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint('uq_users_room_id_username', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'token')
    op.add_column('rooms', sa.Column('tag_groups_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
