"""set cascade del

Revision ID: cba795b0c96f
Revises: 0e1b75932cca
Create Date: 2026-02-21 00:33:52.731632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba795b0c96f'
down_revision: Union[str, Sequence[str], None] = '0e1b75932cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_room_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_room_id_fkey'), 'users', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
