"""update song, add subtitle & album info

Revision ID: d7a450cc35a9
Revises: cba795b0c96f
Create Date: 2026-02-21 23:51:00.360833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd7a450cc35a9'
down_revision: Union[str, Sequence[str], None] = 'cba795b0c96f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('subtitle', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('album_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'album_name')
    op.drop_column('songs', 'subtitle')
    # ### end Alembic commands ###
