"""add_playback_state_json_to_rooms

Revision ID: e801682d6327
Revises: 658994cec749
Create Date: 2026-03-15 10:05:07.323848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e801682d6327'
down_revision: Union[str, Sequence[str], None] = '658994cec749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('playback_state_json', sa.JSON(), nullable=True, comment='持久化播放状态快照，cache miss 时用于恢复'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'playback_state_json')
    # ### end Alembic commands ###
