"""drop tag_group_id column

Revision ID: ebb3be07a6c7
Revises: 9d19923d20fa
Create Date: 2026-02-25 22:05:14.935259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ebb3be07a6c7'
down_revision: Union[str, Sequence[str], None] = '9d19923d20fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rooms_tag_group_id_fkey'),
                       'rooms',
                       type_='foreignkey')
    op.drop_column('rooms', 'tag_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'rooms',
        sa.Column('tag_group_id',
                  sa.INTEGER(),
                  autoincrement=False,
                  nullable=True))
    op.create_foreign_key(op.f('rooms_tag_group_id_fkey'),
                          'rooms',
                          'tag_groups', ['tag_group_id'], ['id'],
                          ondelete='SET NULL')
    # ### end Alembic commands ###
