"""add player_id and room scoped username

Revision ID: ee0c1a143f3d
Revises: 5893cdbc207c
Create Date: 2026-02-24 11:11:08.183304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0c1a143f3d'
down_revision: Union[str, Sequence[str], None] = '5893cdbc207c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('player_id', sa.String(), nullable=True))
    op.execute("UPDATE users SET player_id = username WHERE player_id IS NULL")
    op.alter_column('users', 'player_id', nullable=False)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_unique_constraint('uq_users_player_id', 'users', ['player_id'])
    op.create_unique_constraint('uq_users_room_username', 'users', ['room_id', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_room_username', 'users', type_='unique')
    op.drop_constraint('uq_users_player_id', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'player_id')
    # ### end Alembic commands ###
