"""add song start range

Revision ID: f4206f0da7c2
Revises: dc15b5036dca
Create Date: 2026-02-28 16:14:00.558282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f4206f0da7c2'
down_revision: Union[str, Sequence[str], None] = 'dc15b5036dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms',
                  sa.Column('song_start_range_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'song_start_range_percent')
    # ### end Alembic commands ###
