"""Add current_song_index to Room model

Revision ID: f5534bb260c6
Revises: 59a73e89aff7
Create Date: 2026-03-01 00:29:53.300517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f5534bb260c6'
down_revision: Union[str, Sequence[str], None] = '59a73e89aff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms',
                  sa.Column('current_song_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'current_song_index')
    # ### end Alembic commands ###
